//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjMerchades.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DARNASSUS\\MOTORHEAD;Initial Catalog=db_240098_66_A_1_2024;User ID=240" +
            "098_66_A_1_2024;Password=12345678;Encrypt=True;TrustServerCertificate=True")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DARNASSUS\\MOTORHEAD;Initial Catalog=db_240098_66_A_1_2024;User ID=240" +
            "098_66_A_1_2024;Password=12345678;Encrypt=True;TrustServerCertificate=True")]
        public string db_240098_66_A_1_2024ConnectionString {
            get {
                return ((string)(this["db_240098_66_A_1_2024ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DARNASSUS\\MOTORHEAD;Initial Catalog=db_240098_66_A_1_2024;User ID=240" +
            "098_66_A_1_2024;Password=12345678;Encrypt=True;TrustServerCertificate=True")]
        public string masterConnectionString
        {
            get
            {
                return ((string)(this["masterConnectionString"]));
            }
        }
        public string dboConnectionString {
            get {
                return ((string)(this["dboConnectionString"]));
            }
        }
    }
}
